### PR TITLE
Drop trackio_space_id from the wordle GRPO config, which its transformers pin lacks

### PR DESCRIPTION
**Pull request by danielhanchen**
### The bug

`Openenv_wordle_grpo.ipynb` on a Colab A100 stops at the `GRPOConfig` cell:

```
TypeError: GRPOConfig.__init__() got an unexpected keyword argument 'trackio_space_id'
```

Everything after it is cascade: `NameError: name 'grpo_config' is not defined`,
then `trainer`, then `trainer_stats`.

This is not a regression from #332, and #332 is not implicated. That PR added
the vLLM install the notebook needed at cell 4; with it in place the run now
reaches cell 14, where a second, older defect was waiting.

### Root cause

`trackio_space_id` is not a TRL field. `GRPOConfig` is a dataclass over
`transformers.TrainingArguments`, so its accepted keywords are whatever the
**installed** transformers declares, and this notebook installs

```python
!uv pip install --upgrade --no-deps transformers==4.56.2 ... trl==0.29.1 ...
```

Read out of the published wheels:

| transformers | `trackio_space_id` field | `TRACKIO_SPACE_ID` env var |
| --- | --- | --- |
| 4.56.2 | no | yes, the only mechanism |
| 4.57.0 - 5.0.0 | yes, default `"trackio"` | yes, deprecated, takes precedence |
| 5.5.4 | yes, default `"trackio"` | removed |
| 5.6.0, 5.14.1 | yes, default `None` | removed |

4.56.2 configured the Space through the environment; 4.57.0 introduced the
field. So the notebook asked a 4.56.2 `TrainingArguments` for a keyword that
arrived one release later.

Unsloth is not at fault and needs no shim. It generates `UnslothGRPOConfig` by
reflecting the installed `TrainingArguments`, so under 4.56.2 the keyword falls
through `**kwargs` into `super().__init__` and TRL rejects it, correctly. A
compatibility shim there would have to swallow unknown keywords, which would
also swallow typos, and could not honour the value on transformers 5.5 and
later anyway, where the environment variable it would translate to no longer
exists.

### The fix

Stop passing the field. `report_to = "trackio"` is unchanged, so tracking still
runs; only the Space id is dropped, and each transformers then applies its own
default. The value being dropped was `'outputs'`, the notebook's `output_dir`
copy-pasted into a slot that wants `user/space`, so nothing meaningful is lost.

Raising the pin instead was the other option and was rejected: `transformers==4.56.2`
is a coordinated pin across this repo (see #336), and no single spelling of this
setting works from 4.56.2 through 5.x, so the notebook would only have moved the
problem to the other end of the supported range. The replacement comment records
both spellings for anyone who does want a Space.

Two notebooks and their scripts: `Openenv_wordle_grpo` and the generated
`AMD-Openenv_wordle_grpo`. A search of `nb/`, `kaggle/`, `original_template/`,
`python_scripts/` and `molab/` finds no other file naming `trackio_space_id`,
`project` or `trackio_static_space_id`.

### Regression test

`tests/test_trackio_args_match_pinned_transformers.py` checks every notebook and
script that passes one of the three trackio `TrainingArguments` fields against
its own exact `transformers==` pin, using floors measured from the wheels rather
than release notes. It is a table, so the next such field is one more row.

Before this change it reports 4 failures, on both wordle notebooks and both
scripts. After, none. There is deliberately no assertion that some file still
uses one of these fields, because the fix was to stop using them and zero uses is
the correct steady state; the detectors are exercised against synthetic sources
instead, both ways, so a regex that stopped matching cannot leave the gate
quietly green.

### Test results

```
python -m pytest tests/ -q --ignore=tests/security
10638 passed, 165 skipped in 230.80s
```

### Not verified

I cannot run Colab, so the effect on a live runtime is by construction rather
than observed. What is measured is the version table above, taken from the
wheels on a local machine, and that the removed keyword is the only thing in
that cell absent from 4.56.2. What is not observed:

- that the notebook now gets past cell 14 on a Colab A100 and completes training;
- that `report_to = "trackio"` on transformers 4.56.2 with no Space id logs to a
  local trackio dashboard without asking for a Hub token. That is what the 4.56.2
  source does (`space_id = os.getenv("TRACKIO_SPACE_ID", None)`), but I have not
  watched it happen in a notebook.

### CODE REVIEW

**Comment by danielhanchen** [comment]
### Merge order against the other open PRs

No ordering constraint. Test-merged every pair onto `main` locally, both
directions, and ran the full suite on each combination:

| tree | result |
| --- | --- |
| main + #338 + #339 | merges clean |
| main + #338 + #339 + #337 | 11861 passed, 165 skipped, 0 failed |
| main + #338 + #339 + #335 | 12654 passed, 165 skipped, 0 failed |
| main + #338 + #339 + #336 | 12212 passed, 165 skipped, 0 failed |

#338 and #339 each add one step to `notebooks-tests-ci.yml`, deliberately at
anchors far enough apart that neither collides with the other or with the three
open PRs. Neither touches `update_all_notebooks.py`, so neither can conflict
with #337's generator work.

Worth flagging separately, since it is not visible from any one of them:
**#335, #336 and #337 conflict with each other.** #335 and #336 both insert their
CI step immediately before `test_amd_git_main_unsloth_install` and both
regenerate the same 45 GRPO notebooks, so they collide on the workflow file plus
66 notebooks and scripts. #335 and #337, and #336 and #337, each collide on
`nb/Gemma4_(E2B)_GRPO.ipynb`. Whichever of those lands first, the other two need
a rebase.
